# wp-cliを使用し、wordpressのインストール
- name: install WordPress
  become: no
  command: >
    wp core install --url=http://{{ ansible_fqdn }} --title="{{ wordpress_site_name }}" --admin_user={{ wordpress_site_admin_user }} --admin_password={{ wordpress_site_admin_password }} --admin_email={{ wordpress_site_admin_email }}
    chdir={{ document_root }}{{ wordpress_directory }}
  notify: restart apache
  tags: wordpress
